[pytest]
markers =
    smoke: Smoke tests
    regression: Regression tests
    api: API tests
    order: Order related tests
    user: User related tests
    login: Login tests
    registration: Registration tests

filterwarnings =
    ignore:.*pkg_resources is deprecated.*:UserWarning