[pytest]
addopts = -v -s --alluredir=allure-results --html=test_reports/report.html --self-contained-html
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Smoke tests
    regression: Regression tests
    api: API tests